#syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /src/app/

COPY ./vite.config.js /src/app/vite.config.js
COPY ./tsconfig.json /src/app/tsconfig.json
COPY ./package.json /src/app/package.json
COPY ./cypress.config.ts /src/app/cypress.config.ts
COPY ./nuxt.config.ts /src/app/nuxt.config.ts
COPY ./app.vue /src/app/app.vue
COPY ./stores/ /src/app/stores/
COPY ./server/ /src/app/server/
COPY ./screens/ /src/app/screens/
COPY ./public/ /src/app/public/
COPY ./infrastructure/ /src/app/infrastructure/
COPY ./domains/ /src/app/domains/
COPY ./cypress/ /src/app/cypress/
COPY ./constants/ /src/app/constants/
COPY ./components/ /src/app/components/
COPY ./assets/ /src/app/assets/

RUN npm install -g bun
RUN apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

RUN bun install

CMD bun run test
